name: root-project.org
description: root-project.org blog
url: http://root-project.org
timezone: Europe/Berlin
markdown: redcarpet
pygments: true
permalink: /:year/:month/:day/:categories/:title/
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
